### ISSUE TITLE
AttributeError: 'module' object has no attribute 'control_flow_ops'

### ISSUE THREAD

**Issue by SeekPoint** [Smerity/keras_snli#4]
Missing from GloVe: surf-skiier
Missing from GloVe: Athekwl
Loading GloVe
Total number of null word embeddings:
4043
Traceback (most recent call last):
  File "snli_rnn.py", line 174, in <module>
    prem = BatchNormalization()(prem)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 514, in **call**
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/normalization.py", line 160, in call
    x_normed = K.in_train_phase(x_normed, x_normed_running)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1304, in in_train_phase
    x = tf.python.control_flow_ops.cond(tf.cast(_LEARNING_PHASE, 'bool'),
AttributeError: 'module' object has no attribute 'control_flow_ops'
rzai@rzai00:~/prj/keras_snli$

**Comment by Smerity** [comment]
Your issue has no details. From the look of it, I'm guessing you have an older version of Tensorflow installed. This is most likely not an issue with this codebase but instead your setup.

**Comment by SeekPoint** [comment]
yes, I just change the backend to theano
